{% set name = "deepforest" %}
{% set version = "1.1.1" %}
{% set sha256 = "b9ada406f4d5bb58411cbcdf6814c0c9a0e855c7c12c91db3683d474645f0d0c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py<36 or py>37]
  number: 0
  script:
    - '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python
    - pip >=20.1
    - numpy >=1.14.0

  run:
    - python
    - numpydoc
    - h5py
    - geopandas
    - pandas
    - pillow
    - pip
    - pytorch_lightning
    - torch
    - pyyaml >=5.1.0
    - pytest
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - recommonmark
    - rasterio
    - rtree
    - sphinx >=1.8
    - slidingwindow
    - tqdm
    - torchvision
    - xmltodict
    - imagecodecs
test:
  imports:
    - deepforest
  source_files:
    - tests/*

about:
  home: https://github.com/weecology/DeepForest
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Package for Tree Crown Detection in Airborne RGB imagery
  description: |
    DeepForest is a python package for training and predicting individual
    tree crowns from airborne RGB imagery. DeepForest comes with a prebuilt
    model trained on data from the National Ecological Observation Network.
    Users can extend this model by annotating and training custom models
    starting from the prebuilt model.

    DeepForest es un paquete de python para la predicción
    de coronas de árboles individuales basada en modelos entrenados
    con imágenes remotas RVA ( RGB, por sus siglas en inglés).
    DeepForest viene con un modelo entrenado con datos proveídos por la
    Red Nacional de Observatorios Ecológicos (NEON, por sus siglas en inglés).
    Los usuarios pueden ampliar este modelo pre-construido por anotación
    de etiquetas y entrenamiento con datos locales. La documentación de
    DeepForest está escrita en inglés, sin embargo, agradeceríamos
    contribuciones con fin de hacerla accesible en otros idiomas.
  doc_url: https://deepforest.readthedocs.io/en/latest/
  dev_url: https://github.com/weecology/DeepForest

extra:
  recipe-maintainers:
    - bw4sz
    - henrykironde
