{% set name = "deepforest" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa224f3ae3c099876296f3b821de759a3be780162a19d49b42b313e0fc328d45

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - deepforest = deepforest.scripts.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.15
    - aiohttp
    - aiolimiter
    - faster-coco-eval >=1.6.8
    - geopandas
    - h5py
    - huggingface_hub >=0.25.0
    - hydra-core
    - kornia >=0.8.2
    - matplotlib-base
    - numpy
    - omegaconf
    - opencv >=4.5.4
    - pandas
    - pillow >6.2.0
    - psutil
    - pytorch >=2.2.0
    - pytorch-lightning >=2.6.0,<3.0.0
    - pyyaml >=5.1.0
    - rasterio
    - safetensors >=0.8.0
    - setuptools
    - shapely >2.0.0
    - slidingwindow
    - supervision
    - tensorboard
    - timm
    - torchvision >=0.17.0
    - tqdm
    - transformers !=5.1.0,!=4.57
    - xmltodict

test:
  requires:
    - python {{ python_min }}
  imports:
    - deepforest
    - deepforest.main
  commands:
    - deepforest --help

about:
  home: https://github.com/weecology/DeepForest
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Package for Tree Crown Detection in Airborne RGB imagery
  description: |
    DeepForest is a python package for training and predicting individual
    tree crowns from airborne RGB imagery. DeepForest comes with a prebuilt
    model trained on data from the National Ecological Observation Network.
    Users can extend this model by annotating and training custom models
    starting from the prebuilt model.

    DeepForest es un paquete de python para la predicción
    de coronas de árboles individuales basada en modelos entrenados
    con imágenes remotas RVA ( RGB, por sus siglas en inglés).
    DeepForest viene con un modelo entrenado con datos proveídos por la
    Red Nacional de Observatorios Ecológicos (NEON, por sus siglas en inglés).
    Los usuarios pueden ampliar este modelo pre-construido por anotación
    de etiquetas y entrenamiento con datos locales. La documentación de
    DeepForest está escrita en inglés, sin embargo, agradeceríamos
    contribuciones con fin de hacerla accesible en otros idiomas.
  doc_url: https://deepforest.readthedocs.io/en/latest/
  dev_url: https://github.com/weecology/DeepForest

extra:
  recipe-maintainers:
    - bw4sz
    - henrykironde
    - ethanwhite
